/* eslint-disable */

/* prettier-ignore-start */

/* prettier-ignore-end */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as SelectOrgRoute } from "./routes/select-org";
import { Route as SignupRoute } from "./routes/signup";
import { Route as ResetPasswordRoute } from "./routes/reset-password";
import { Route as LoginRoute } from "./routes/login";
import { Route as ForgotPasswordRoute } from "./routes/forgot-password";
import { Route as IndexRoute } from "./routes/index";
import { Route as AuthenticatedRoute } from "./routes/_authenticated";
import { Route as AuthenticatedDashboardRoute } from "./routes/_authenticated/dashboard";
import { Route as AuthenticatedCreateOrganizationRoute } from "./routes/_authenticated/create-organization";
import { Route as AuthenticatedSuperadminRoute } from "./routes/_authenticated/_superadmin";
import { Route as AuthenticatedAdminRoute } from "./routes/_authenticated/_admin";
import { Route as AuthenticatedSettingsProfileRoute } from "./routes/_authenticated/settings/profile";
import { Route as AuthenticatedSettingsPasswordRoute } from "./routes/_authenticated/settings/password";
import { Route as AuthenticatedSettingsOrganizationRoute } from "./routes/_authenticated/settings/organization";
import { Route as AuthenticatedSuperadminSuperadminIndexRoute } from "./routes/_authenticated/_superadmin/superadmin/index";
import { Route as AuthenticatedSuperadminSuperadminSettingsRoute } from "./routes/_authenticated/_superadmin/superadmin/settings";
import { Route as AuthenticatedSuperadminSuperadminOrganizationsIndexRoute } from "./routes/_authenticated/_superadmin/superadmin/organizations/index";
import { Route as AuthenticatedSuperadminSuperadminUsersIndexRoute } from "./routes/_authenticated/_superadmin/superadmin/users/index";
import { Route as AuthenticatedSuperadminSuperadminRolesIndexRoute } from "./routes/_authenticated/_superadmin/superadmin/roles/index";
import { Route as AuthenticatedSuperadminSuperadminOrganizationsOrgIdRoute } from "./routes/_authenticated/_superadmin/superadmin/organizations/$orgId";
import { Route as AuthenticatedSuperadminSuperadminUsersUserIdRoute } from "./routes/_authenticated/_superadmin/superadmin/users/$userId";
import { Route as AuthenticatedSuperadminSuperadminRolesRoleIdRoute } from "./routes/_authenticated/_superadmin/superadmin/roles/$roleId";

// Create/Update Routes

const SelectOrgRouteWithChildren = SelectOrgRoute;
const SignupRouteWithChildren = SignupRoute;
const ResetPasswordRouteWithChildren = ResetPasswordRoute;
const LoginRouteWithChildren = LoginRoute;
const ForgotPasswordRouteWithChildren = ForgotPasswordRoute;
const IndexRouteWithChildren = IndexRoute;

const AuthenticatedSuperadminRouteChildren = {
	AuthenticatedSuperadminSuperadminIndexRoute,
	AuthenticatedSuperadminSuperadminSettingsRoute,
	AuthenticatedSuperadminSuperadminOrganizationsIndexRoute,
	AuthenticatedSuperadminSuperadminUsersIndexRoute,
	AuthenticatedSuperadminSuperadminRolesIndexRoute,
	AuthenticatedSuperadminSuperadminOrganizationsOrgIdRoute,
	AuthenticatedSuperadminSuperadminUsersUserIdRoute,
	AuthenticatedSuperadminSuperadminRolesRoleIdRoute,
};

const AuthenticatedSuperadminRouteWithChildren =
	AuthenticatedSuperadminRoute._addFileChildren(
		AuthenticatedSuperadminRouteChildren,
	);

const AuthenticatedAdminRouteWithChildren = AuthenticatedAdminRoute;

const AuthenticatedRouteChildren = {
	AuthenticatedDashboardRoute,
	AuthenticatedCreateOrganizationRoute,
	AuthenticatedSuperadminRoute: AuthenticatedSuperadminRouteWithChildren,
	AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
	AuthenticatedSettingsProfileRoute,
	AuthenticatedSettingsPasswordRoute,
	AuthenticatedSettingsOrganizationRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
	AuthenticatedRouteChildren,
);

// Create and export the route tree

export const routeTree = rootRoute._addFileChildren({
	IndexRoute: IndexRouteWithChildren,
	LoginRoute: LoginRouteWithChildren,
	SignupRoute: SignupRouteWithChildren,
	ForgotPasswordRoute: ForgotPasswordRouteWithChildren,
	ResetPasswordRoute: ResetPasswordRouteWithChildren,
	SelectOrgRoute: SelectOrgRouteWithChildren,
	AuthenticatedRoute: AuthenticatedRouteWithChildren,
});
