/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SelectOrgRouteImport } from './routes/select-org'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCreateOrganizationRouteImport } from './routes/_authenticated/create-organization'
import { Route as AuthenticatedSuperadminRouteImport } from './routes/_authenticated/_superadmin'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile'
import { Route as AuthenticatedSettingsPasswordRouteImport } from './routes/_authenticated/settings/password'
import { Route as AuthenticatedSettingsOrganizationRouteImport } from './routes/_authenticated/settings/organization'
import { Route as AuthenticatedSuperadminSuperadminIndexRouteImport } from './routes/_authenticated/_superadmin/superadmin/index'
import { Route as AuthenticatedSuperadminSuperadminSettingsRouteImport } from './routes/_authenticated/_superadmin/superadmin/settings'
import { Route as AuthenticatedSuperadminSuperadminUsersIndexRouteImport } from './routes/_authenticated/_superadmin/superadmin/users/index'
import { Route as AuthenticatedSuperadminSuperadminRolesIndexRouteImport } from './routes/_authenticated/_superadmin/superadmin/roles/index'
import { Route as AuthenticatedSuperadminSuperadminOrganizationsIndexRouteImport } from './routes/_authenticated/_superadmin/superadmin/organizations/index'
import { Route as AuthenticatedSuperadminSuperadminUsersUserIdRouteImport } from './routes/_authenticated/_superadmin/superadmin/users/$userId'
import { Route as AuthenticatedSuperadminSuperadminRolesRoleIdRouteImport } from './routes/_authenticated/_superadmin/superadmin/roles/$roleId'
import { Route as AuthenticatedSuperadminSuperadminOrganizationsOrgIdRouteImport } from './routes/_authenticated/_superadmin/superadmin/organizations/$orgId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectOrgRoute = SelectOrgRouteImport.update({
  id: '/select-org',
  path: '/select-org',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreateOrganizationRoute =
  AuthenticatedCreateOrganizationRouteImport.update({
    id: '/create-organization',
    path: '/create-organization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperadminRoute = AuthenticatedSuperadminRouteImport.update({
  id: '/_superadmin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsPasswordRoute =
  AuthenticatedSettingsPasswordRouteImport.update({
    id: '/settings/password',
    path: '/settings/password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsOrganizationRoute =
  AuthenticatedSettingsOrganizationRouteImport.update({
    id: '/settings/organization',
    path: '/settings/organization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperadminSuperadminIndexRoute =
  AuthenticatedSuperadminSuperadminIndexRouteImport.update({
    id: '/superadmin/',
    path: '/superadmin/',
    getParentRoute: () => AuthenticatedSuperadminRoute,
  } as any)
const AuthenticatedSuperadminSuperadminSettingsRoute =
  AuthenticatedSuperadminSuperadminSettingsRouteImport.update({
    id: '/superadmin/settings',
    path: '/superadmin/settings',
    getParentRoute: () => AuthenticatedSuperadminRoute,
  } as any)
const AuthenticatedSuperadminSuperadminUsersIndexRoute =
  AuthenticatedSuperadminSuperadminUsersIndexRouteImport.update({
    id: '/superadmin/users/',
    path: '/superadmin/users/',
    getParentRoute: () => AuthenticatedSuperadminRoute,
  } as any)
const AuthenticatedSuperadminSuperadminRolesIndexRoute =
  AuthenticatedSuperadminSuperadminRolesIndexRouteImport.update({
    id: '/superadmin/roles/',
    path: '/superadmin/roles/',
    getParentRoute: () => AuthenticatedSuperadminRoute,
  } as any)
const AuthenticatedSuperadminSuperadminOrganizationsIndexRoute =
  AuthenticatedSuperadminSuperadminOrganizationsIndexRouteImport.update({
    id: '/superadmin/organizations/',
    path: '/superadmin/organizations/',
    getParentRoute: () => AuthenticatedSuperadminRoute,
  } as any)
const AuthenticatedSuperadminSuperadminUsersUserIdRoute =
  AuthenticatedSuperadminSuperadminUsersUserIdRouteImport.update({
    id: '/superadmin/users/$userId',
    path: '/superadmin/users/$userId',
    getParentRoute: () => AuthenticatedSuperadminRoute,
  } as any)
const AuthenticatedSuperadminSuperadminRolesRoleIdRoute =
  AuthenticatedSuperadminSuperadminRolesRoleIdRouteImport.update({
    id: '/superadmin/roles/$roleId',
    path: '/superadmin/roles/$roleId',
    getParentRoute: () => AuthenticatedSuperadminRoute,
  } as any)
const AuthenticatedSuperadminSuperadminOrganizationsOrgIdRoute =
  AuthenticatedSuperadminSuperadminOrganizationsOrgIdRouteImport.update({
    id: '/superadmin/organizations/$orgId',
    path: '/superadmin/organizations/$orgId',
    getParentRoute: () => AuthenticatedSuperadminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-org': typeof SelectOrgRoute
  '/signup': typeof SignupRoute
  '/create-organization': typeof AuthenticatedCreateOrganizationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/superadmin/settings': typeof AuthenticatedSuperadminSuperadminSettingsRoute
  '/superadmin/': typeof AuthenticatedSuperadminSuperadminIndexRoute
  '/superadmin/organizations/$orgId': typeof AuthenticatedSuperadminSuperadminOrganizationsOrgIdRoute
  '/superadmin/roles/$roleId': typeof AuthenticatedSuperadminSuperadminRolesRoleIdRoute
  '/superadmin/users/$userId': typeof AuthenticatedSuperadminSuperadminUsersUserIdRoute
  '/superadmin/organizations/': typeof AuthenticatedSuperadminSuperadminOrganizationsIndexRoute
  '/superadmin/roles/': typeof AuthenticatedSuperadminSuperadminRolesIndexRoute
  '/superadmin/users/': typeof AuthenticatedSuperadminSuperadminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-org': typeof SelectOrgRoute
  '/signup': typeof SignupRoute
  '/create-organization': typeof AuthenticatedCreateOrganizationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/superadmin/settings': typeof AuthenticatedSuperadminSuperadminSettingsRoute
  '/superadmin': typeof AuthenticatedSuperadminSuperadminIndexRoute
  '/superadmin/organizations/$orgId': typeof AuthenticatedSuperadminSuperadminOrganizationsOrgIdRoute
  '/superadmin/roles/$roleId': typeof AuthenticatedSuperadminSuperadminRolesRoleIdRoute
  '/superadmin/users/$userId': typeof AuthenticatedSuperadminSuperadminUsersUserIdRoute
  '/superadmin/organizations': typeof AuthenticatedSuperadminSuperadminOrganizationsIndexRoute
  '/superadmin/roles': typeof AuthenticatedSuperadminSuperadminRolesIndexRoute
  '/superadmin/users': typeof AuthenticatedSuperadminSuperadminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-org': typeof SelectOrgRoute
  '/signup': typeof SignupRoute
  '/_authenticated/_superadmin': typeof AuthenticatedSuperadminRouteWithChildren
  '/_authenticated/create-organization': typeof AuthenticatedCreateOrganizationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/_authenticated/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/_superadmin/superadmin/settings': typeof AuthenticatedSuperadminSuperadminSettingsRoute
  '/_authenticated/_superadmin/superadmin/': typeof AuthenticatedSuperadminSuperadminIndexRoute
  '/_authenticated/_superadmin/superadmin/organizations/$orgId': typeof AuthenticatedSuperadminSuperadminOrganizationsOrgIdRoute
  '/_authenticated/_superadmin/superadmin/roles/$roleId': typeof AuthenticatedSuperadminSuperadminRolesRoleIdRoute
  '/_authenticated/_superadmin/superadmin/users/$userId': typeof AuthenticatedSuperadminSuperadminUsersUserIdRoute
  '/_authenticated/_superadmin/superadmin/organizations/': typeof AuthenticatedSuperadminSuperadminOrganizationsIndexRoute
  '/_authenticated/_superadmin/superadmin/roles/': typeof AuthenticatedSuperadminSuperadminRolesIndexRoute
  '/_authenticated/_superadmin/superadmin/users/': typeof AuthenticatedSuperadminSuperadminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/select-org'
    | '/signup'
    | '/create-organization'
    | '/dashboard'
    | '/settings/organization'
    | '/settings/password'
    | '/settings/profile'
    | '/superadmin/settings'
    | '/superadmin/'
    | '/superadmin/organizations/$orgId'
    | '/superadmin/roles/$roleId'
    | '/superadmin/users/$userId'
    | '/superadmin/organizations/'
    | '/superadmin/roles/'
    | '/superadmin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/select-org'
    | '/signup'
    | '/create-organization'
    | '/dashboard'
    | '/settings/organization'
    | '/settings/password'
    | '/settings/profile'
    | '/superadmin/settings'
    | '/superadmin'
    | '/superadmin/organizations/$orgId'
    | '/superadmin/roles/$roleId'
    | '/superadmin/users/$userId'
    | '/superadmin/organizations'
    | '/superadmin/roles'
    | '/superadmin/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/select-org'
    | '/signup'
    | '/_authenticated/_superadmin'
    | '/_authenticated/create-organization'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings/organization'
    | '/_authenticated/settings/password'
    | '/_authenticated/settings/profile'
    | '/_authenticated/_superadmin/superadmin/settings'
    | '/_authenticated/_superadmin/superadmin/'
    | '/_authenticated/_superadmin/superadmin/organizations/$orgId'
    | '/_authenticated/_superadmin/superadmin/roles/$roleId'
    | '/_authenticated/_superadmin/superadmin/users/$userId'
    | '/_authenticated/_superadmin/superadmin/organizations/'
    | '/_authenticated/_superadmin/superadmin/roles/'
    | '/_authenticated/_superadmin/superadmin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SelectOrgRoute: typeof SelectOrgRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-org': {
      id: '/select-org'
      path: '/select-org'
      fullPath: '/select-org'
      preLoaderRoute: typeof SelectOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/create-organization': {
      id: '/_authenticated/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof AuthenticatedCreateOrganizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_superadmin': {
      id: '/_authenticated/_superadmin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedSuperadminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/password': {
      id: '/_authenticated/settings/password'
      path: '/settings/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof AuthenticatedSettingsPasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/organization': {
      id: '/_authenticated/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_superadmin/superadmin/': {
      id: '/_authenticated/_superadmin/superadmin/'
      path: '/superadmin'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof AuthenticatedSuperadminSuperadminIndexRouteImport
      parentRoute: typeof AuthenticatedSuperadminRoute
    }
    '/_authenticated/_superadmin/superadmin/settings': {
      id: '/_authenticated/_superadmin/superadmin/settings'
      path: '/superadmin/settings'
      fullPath: '/superadmin/settings'
      preLoaderRoute: typeof AuthenticatedSuperadminSuperadminSettingsRouteImport
      parentRoute: typeof AuthenticatedSuperadminRoute
    }
    '/_authenticated/_superadmin/superadmin/users/': {
      id: '/_authenticated/_superadmin/superadmin/users/'
      path: '/superadmin/users'
      fullPath: '/superadmin/users/'
      preLoaderRoute: typeof AuthenticatedSuperadminSuperadminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedSuperadminRoute
    }
    '/_authenticated/_superadmin/superadmin/roles/': {
      id: '/_authenticated/_superadmin/superadmin/roles/'
      path: '/superadmin/roles'
      fullPath: '/superadmin/roles/'
      preLoaderRoute: typeof AuthenticatedSuperadminSuperadminRolesIndexRouteImport
      parentRoute: typeof AuthenticatedSuperadminRoute
    }
    '/_authenticated/_superadmin/superadmin/organizations/': {
      id: '/_authenticated/_superadmin/superadmin/organizations/'
      path: '/superadmin/organizations'
      fullPath: '/superadmin/organizations/'
      preLoaderRoute: typeof AuthenticatedSuperadminSuperadminOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedSuperadminRoute
    }
    '/_authenticated/_superadmin/superadmin/users/$userId': {
      id: '/_authenticated/_superadmin/superadmin/users/$userId'
      path: '/superadmin/users/$userId'
      fullPath: '/superadmin/users/$userId'
      preLoaderRoute: typeof AuthenticatedSuperadminSuperadminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedSuperadminRoute
    }
    '/_authenticated/_superadmin/superadmin/roles/$roleId': {
      id: '/_authenticated/_superadmin/superadmin/roles/$roleId'
      path: '/superadmin/roles/$roleId'
      fullPath: '/superadmin/roles/$roleId'
      preLoaderRoute: typeof AuthenticatedSuperadminSuperadminRolesRoleIdRouteImport
      parentRoute: typeof AuthenticatedSuperadminRoute
    }
    '/_authenticated/_superadmin/superadmin/organizations/$orgId': {
      id: '/_authenticated/_superadmin/superadmin/organizations/$orgId'
      path: '/superadmin/organizations/$orgId'
      fullPath: '/superadmin/organizations/$orgId'
      preLoaderRoute: typeof AuthenticatedSuperadminSuperadminOrganizationsOrgIdRouteImport
      parentRoute: typeof AuthenticatedSuperadminRoute
    }
  }
}

interface AuthenticatedSuperadminRouteChildren {
  AuthenticatedSuperadminSuperadminSettingsRoute: typeof AuthenticatedSuperadminSuperadminSettingsRoute
  AuthenticatedSuperadminSuperadminIndexRoute: typeof AuthenticatedSuperadminSuperadminIndexRoute
  AuthenticatedSuperadminSuperadminOrganizationsOrgIdRoute: typeof AuthenticatedSuperadminSuperadminOrganizationsOrgIdRoute
  AuthenticatedSuperadminSuperadminRolesRoleIdRoute: typeof AuthenticatedSuperadminSuperadminRolesRoleIdRoute
  AuthenticatedSuperadminSuperadminUsersUserIdRoute: typeof AuthenticatedSuperadminSuperadminUsersUserIdRoute
  AuthenticatedSuperadminSuperadminOrganizationsIndexRoute: typeof AuthenticatedSuperadminSuperadminOrganizationsIndexRoute
  AuthenticatedSuperadminSuperadminRolesIndexRoute: typeof AuthenticatedSuperadminSuperadminRolesIndexRoute
  AuthenticatedSuperadminSuperadminUsersIndexRoute: typeof AuthenticatedSuperadminSuperadminUsersIndexRoute
}

const AuthenticatedSuperadminRouteChildren: AuthenticatedSuperadminRouteChildren =
  {
    AuthenticatedSuperadminSuperadminSettingsRoute:
      AuthenticatedSuperadminSuperadminSettingsRoute,
    AuthenticatedSuperadminSuperadminIndexRoute:
      AuthenticatedSuperadminSuperadminIndexRoute,
    AuthenticatedSuperadminSuperadminOrganizationsOrgIdRoute:
      AuthenticatedSuperadminSuperadminOrganizationsOrgIdRoute,
    AuthenticatedSuperadminSuperadminRolesRoleIdRoute:
      AuthenticatedSuperadminSuperadminRolesRoleIdRoute,
    AuthenticatedSuperadminSuperadminUsersUserIdRoute:
      AuthenticatedSuperadminSuperadminUsersUserIdRoute,
    AuthenticatedSuperadminSuperadminOrganizationsIndexRoute:
      AuthenticatedSuperadminSuperadminOrganizationsIndexRoute,
    AuthenticatedSuperadminSuperadminRolesIndexRoute:
      AuthenticatedSuperadminSuperadminRolesIndexRoute,
    AuthenticatedSuperadminSuperadminUsersIndexRoute:
      AuthenticatedSuperadminSuperadminUsersIndexRoute,
  }

const AuthenticatedSuperadminRouteWithChildren =
  AuthenticatedSuperadminRoute._addFileChildren(
    AuthenticatedSuperadminRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedSuperadminRoute: typeof AuthenticatedSuperadminRouteWithChildren
  AuthenticatedCreateOrganizationRoute: typeof AuthenticatedCreateOrganizationRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsOrganizationRoute: typeof AuthenticatedSettingsOrganizationRoute
  AuthenticatedSettingsPasswordRoute: typeof AuthenticatedSettingsPasswordRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSuperadminRoute: AuthenticatedSuperadminRouteWithChildren,
  AuthenticatedCreateOrganizationRoute: AuthenticatedCreateOrganizationRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsOrganizationRoute:
    AuthenticatedSettingsOrganizationRoute,
  AuthenticatedSettingsPasswordRoute: AuthenticatedSettingsPasswordRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SelectOrgRoute: SelectOrgRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
